name: apk_manager_example
description: "Demonstrates how to use the apk_manager plugin."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  apk_manager:
    path: ../
  file_picker: ^10.0.0
  permission_handler: ^11.4.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
