name: apk_manager
description: A Flutter plugin that allows you to manage and install apps on Android devices.
version: 0.0.1
homepage: https://wearetoni.com/
repository: https://github.com/toni-experience-software/apk_manager
issue_tracker: https://github.com/toni-experience-software/apk_manager/issues

platforms:
  android:

topics:
  - flutter
  - android
  - apk

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  pigeon: ^25.3.1

flutter:
  plugin:
    platforms:
      android:
        package: com.wearetoni.apk_manager
        pluginClass: ApkManagerPlugin
